spring:
  datasource:
    url: jdbc:sqlite:db/tsp.sqlite3
    driver-class-name: org.sqlite.JDBC
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
